-- E-Ticaret Sistemi Veritabanı Başlatma Scripti
-- PostgreSQL init script for e-ticaret microservices
-- Tek DB: eticaret

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS seller;
CREATE SCHEMA IF NOT EXISTS review;
CREATE SCHEMA IF NOT EXISTS search;
CREATE SCHEMA IF NOT EXISTS order_payment;
CREATE SCHEMA IF NOT EXISTS notification;

GRANT ALL PRIVILEGES ON SCHEMA auth TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA catalog TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA seller TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA review TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA search TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA order_payment TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA notification TO postgres;

ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA seller GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA review GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA search GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA order_payment GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA notification GRANT ALL ON TABLES TO postgres;

ALTER DATABASE eticaret SET search_path TO auth, catalog, seller, review, search, order_payment, notification, public;
